#!/bin/dash

# check the quantity of argv
if [ $# -ne 0 ];then
    echo "usage: shrug-status"
    exit 1
fi

# compare file $1 mode
file_compare(){
    error=2
    same=1
    differ=0

    # argv1 = 1: compare file between current dir and index dir
    if [ $1 -eq 1 ];then
        if [ -z "`find .shrug/index -name $2`" ];then
            echo $error
        else
            diff ".shrug/index/$2" "$2" >/dev/null 2>/dev/null
            if [ $? != 0 ];then
                echo $same
            else
                echo $differ
            fi
        fi
    fi
     # argv1 = 2: compare files between current dir and last commit 
    if [ $1 -eq 2 ];then
        if [ -z "`find ".shrug/commits/commit$3" -name $2`" ];then
            echo $error
        else
            diff ".shrug/commits/commit$3/$2" "$2" >/dev/null 2>/dev/null
            if [ $? != 0 ];then
                echo $same
            else
                echo $differ
            fi
        fi
    fi
    # argv1 = 3: compare files between index dir and last commit 
    if [ $1 -eq 3 ];then
        if [ ! -z "`find ".shrug/commits/commit$3" -name $2`" ] && [ ! -z "`find .shrug/index -name $2`" ];then
            diff ".shrug/index/$2" ".shrug/commits/commit$3/$2" >/dev/null 2>/dev/null
            if [ $? != 0 ];then
                echo $same
            else
                echo $differ
            fi
        else
            echo $error
        fi
    fi
}

status_show()
{	
    work_index=$(file_compare 1 $1 $lastestcommit)
    work_last=$(file_compare 2 $1 $lastestcommit)
    index_last=$(file_compare 3 $1 $lastestcommit)
	file=$1

	if [ ! -e $file ] && [ $index_last -eq 0 ];then
		echo "$file - file deleted"
	elif [ ! -e $file ] && [ ! -e ".shrug/index/$file" ];then
		echo "$file - deleted"
	elif [ $work_last -eq 0 ] && [ $index_last -eq 0 ];then
		echo "$file - same as repo"
	elif [ -e $file ] && [ $work_index -eq 2 ];then
		echo "$file - untracked"
	elif [ $work_index -eq 0 ] && [ $work_last -eq 2 ];then
		echo "$file - added to index"
	elif [ $work_index -eq 1 ] && [ $index_last -eq 0 ];then
		echo "$file - file changed, changes not staged for commit"
	elif [ $work_index -eq 0 ] && [ $index_last -eq 1 ];then
		echo "$file - file changed, changes staged for commit"
	elif [ $work_index -eq 1 ] && [ $index_last -eq 1 ];then 
		echo "$file - file changed, different changes staged for commit"
	fi
}

if [ -e '.shrug/commits/log.txt' ];then
    lastestcommit=`cat '.shrug/commits/log.txt'| head -n1| cut -d' ' -f1`
fi
if [ ! -d '.shrug' ];then 
    echo "$0: error: no .shrug directory containing shrug repository exists"
    exit 1
fi
if [ ! -d '.shrug/commits/commit0' ];then 
    echo "$0: error: your repository does not have any commits yet"
    exit 1
fi
    
for file in `ls`;do
    name="$name:$file"
done

for file in `ls .shrug/index`;do
    name="$name:$file"
done
if [ $lastestcommit -ge 0 ];then
	for file in `ls ".shrug/commits/commit$lastestcommit"`;do
        name="$name:$file"
	done
fi

list=`echo "$name" | tr ":" "\n" | sort | uniq`
for file in $list;do
    status_show $file
done